# **Day6 - Pranay Shah**

!pip install numpy

**NumPy**   
       
        stands for Numerical Python and is used to perform a wide variety of mathematical operations on arrays. It adds powerful data structures to Python that guarantee efficient calculations with arrays and matrices and it supplies an enormous library of high-level mathematical functions that operate on these arrays and matrices.

How to install NumPy?

pip install numpy

Ex1

In [2]:
# create single dimensional array

import numpy as np         #  here "numpy" is a module and "np" is an alias

first=np.array([100,200,300,400])
print(first)

for i in range(0,first.__len__()):
    print(first[i])

print(type(first))
print("dimension of array is\t",first.ndim)
print("\n")
print("shape of array is\t",first.shape)

# first[4]=500     #  arrays are fixed

[100 200 300 400]
100
200
300
400
<class 'numpy.ndarray'>
dimension of array is	 1


shape of array is	 (4,)


In [ ]:
row = 6 

for i in range(6):
    print(' '*())

In [4]:
first = np.array([10,20,30,40,50,70])

print(first)

for i in range(0, first.__len__()):
    print(first[i])

[10 20 30 40 50 70]
10
20
30
40
50
70


Ex1a

In [6]:
# create single dimensional array

import numpy as np         #  here "numpy" is a module and "np" is an alias

first=np.array((100,200,300,400))
print(first) 

for i in range(0,first.__len__()):
    print(first[i])

print(type(first))
print("dimension of array is\t",first.ndim)
print("\n")
print("shape of array is\t",first.shape)

# first[4]=500     #  arrays are fixed



[100 200 300 400]
100
200
300
400
<class 'numpy.ndarray'>
dimension of array is	 1


shape of array is	 (4,)


Ex1b

In [7]:
# create single dimensional array

import numpy as np         

# The elements of a NumPy array can also be booleans, strings, or other objects.

first=np.array([100,3.4,"hello",True])
print(first)

for i in range(0,first.__len__()):
    print(first[i])

print(type(first))
print("dimension of array is\t",first.ndim)
print("\n")
print("shape of array is\t",first.shape)

# first[4]=500     #  arrays are fixed



['100' '3.4' 'hello' 'True']
100
3.4
hello
True
<class 'numpy.ndarray'>
dimension of array is	 1


shape of array is	 (4,)


Ex1c

In [8]:
import numpy as k
#indexing in numpy array

arr1=k.array([10,20,30,40])
print(arr1)
print(arr1[0])
print(arr1[-1])
print("from the begining")
for i in range(0,arr1.__len__()):
    print(arr1[i])
print("from the end")
for i in range(-1,-(arr1.__len__()+1),-1):
    print(arr1[i])

[10 20 30 40]
10
40
from the begining
10
20
30
40
from the end
40
30
20
10


Ex2

In [12]:
# How to accept input in the array

import numpy as np

first=np.arange(10)
print(first)

first=np.arange(5)
print(first)

print("enter 5 numbers")
for i in range(0,first.__len__()):
    first[i]=int(input())

print("Displaying all the numbers")

for i in range(0,first.__len__()):
    print(first[i])

print("\n")
print("dimension of array is\t",first.ndim)

print("\n")
print("shape of array is\t",first.shape)


[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]
enter 5 numbers
Displaying all the numbers
10
20
304
50
60


dimension of array is	 1


shape of array is	 (5,)


Ex3

In [13]:
import numpy as np

first=np.array([[10,20,30],[40,50,60]])    #  here we've passed list of list
print(first)
print("\n")
for i in range(0,first.__len__()):
    for j in range(0,first[i].__len__()):
        print(first[i][j],"\t",end="")
    print("\n")

print("Type of the array is",type(first))
print("\n")
print("dimension of array is\t",first.ndim)
print("\n")
print("shape of array is\t",first.shape)


[[10 20 30]
 [40 50 60]]


10 	20 	30 	

40 	50 	60 	

Type of the array is <class 'numpy.ndarray'>


dimension of array is	 2


shape of array is	 (2, 3)


In [15]:
firts = np.array([[1,2,3,4],[4,5,6,7]])

print(firts)


[[1 2 3 4]
 [4 5 6 7]]


Ex3a

In [23]:
# how to accept values from user inside two-d array

from numpy import *
list=[]

print("how many rows")
rownum=int(input("enter value for a row : "))

print("how many cols")
colnum=int((input("enter value for a column : ")))

print("Enter\t",rownum*colnum," values")
for i in range(1,(rownum*colnum)+1):
        num=int(input())
        list.append(num)

mainarray=array([list])
print(mainarray)

mainarray=mainarray.reshape(rownum,colnum)
print("\n")
print(mainarray)

how many rows
how many cols
Enter	 4  values
[[10 20 30 40]]


[[10 20]
 [30 40]]


Ex4

In [24]:
# initialize one-d array with zero

import numpy as np
first=np.zeros((1,4))                             # one row , 4 columns

print(first)
print("\n")

# initialize two-d array with zeros

second=np.zeros((3,4))                            # 3 rows and 4 columns

print(second)

[[0. 0. 0. 0.]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


Ex4a

In [25]:
# initialize one-d and 2d array  with one  

import numpy as np
first=np.ones((1,4))                             # one row , 4 columns

print(first)
print("\n")

# initialize two-d array with zeros

second=np.ones((3,4))                            # 3 rows and 4 columns

print(second)

[[1. 1. 1. 1.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


Ex5

In [26]:
# initialize arrays with a specific number

import numpy as np

first=np.full((1,4),20)         #  1 row, 4 columns , all should be initialized with 20
print(first)

print("\n")

second=np.full((3,2),15)        #  3 rows, 2 columns, all should be initialized with 15
print(second)

[[20 20 20 20]]


[[15 15]
 [15 15]
 [15 15]]


Ex6

In [27]:
# arange to give range of numbers
import numpy as np
first=np.arange(20,25)    # here 25 is exclusive
print(first)

second=np.arange(10,20,2)       # start with 10, increment by 2 and here 20 is exclusive
print(second)



[20 21 22 23 24]
[10 12 14 16 18]


Ex7

In [28]:
""" If you only use the arange function, it will output a one-dimensional array. To make it a two-dimensional array, 
chain its output with the reshape function. """

import numpy as np
first=np.arange(10,91,10).reshape(3,3)  # 3 rows,3 cols ,  10 to 90 values with 10 as a skip value
print(first)


[[10 20 30]
 [40 50 60]
 [70 80 90]]


Ex8

In [36]:
# array with strings and chars


import numpy as np
first=np.full((1,4),"hello")
print(first)
print("\n")
second=np.array(['A','B','C','D','E','F'])
print(second)
print("\n")
third=np.full((3,2),'A')
print(third)


[['hello' 'hello' 'hello' 'hello']]


['A' 'B' 'C' 'D' 'E' 'F']


[['A' 'A']
 ['A' 'A']
 ['A' 'A']]


Ex9

In [38]:
# initialize numpy array with random numbers
import numpy as np
first=np.random.randint(1,100,10)   # range for random numbers is 1 to 100 and 10 is how many random numbers to be generated
print(first)
print("Double Dimension array")

second=np.random.randint(1,100,12).reshape(3,4)
print(second)

[38 90 61  1 89 18 50 86 78 94]
Double Dimension array
[[64 13  1 80]
 [72 53 19 92]
 [85 87 37 88]]


Ex9a

How are we getting same output on duifferent devices while using (random.randint seed )

In [48]:
""" randint() function generates new set of random numbers everytime. If we want to fix the generation of random numbers,
we should use "seed()" function by passing any number as an argument. """

from numpy import *

random.seed(5)    # this can be any number  , try commenting this   

first=random.randint(1,100,12)
print(first)     # no matter how many times we execute the code, it will display same set of numbers
print("size of the array is\t",first.size)



[79 62 17 74  9 63 28 31 81  8 77 16]
size of the array is	 12


Ex10

REshape function returns new array, while shape function chnages the same array

In [51]:
# checking the shape of numpy array

import numpy as np
first=np.array([100,200,300,400,500,600])
print(id(first))
print(first)
print(first.shape)
print()

print("let's check with double dimension array")
second=np.array([[10,20,30],[40,50,60]])
print(id(first))
print(second)
print(second.shape)
print()

print("Let's convert one-d array's shapes")
first.shape=(2,3)
print(id(first))
print(first)
print("Let's convert two-d array's shape")
second.shape=(3,2)
print(id(first))
print(second)
print(second.ndim)

2486621941232
[100 200 300 400 500 600]
(6,)

let's check with double dimension array
2486621941232
[[10 20 30]
 [40 50 60]]
(2, 3)

Let's convert one-d array's shapes
2486621941232
[[100 200 300]
 [400 500 600]]
Let's convert two-d array's shape
2486621941232
[[10 20]
 [30 40]
 [50 60]]
2


Ex12

In [53]:
#  "intersect1d()" to find out common elements between two arrays

import numpy as np
first=np.array([4,5,8,12,15])
second=np.array([11,15,4,8,9])
third=np.intersect1d(first,second)
print(third)


[ 4  8 15]


Ex13

In [55]:
#  "setdiff1d()" to find out unique elements in first array
# result is always sorted

import numpy as np
first=np.array([4,25,8,32,15])
second=np.array([11,25,1,2,4,8,9])
third=np.setdiff1d(first,second)      #  unique elements inside "first"  array
print(third)
print("\n")
fourth=np.setdiff1d(second,first)     # unique elements inside "second" array
print(fourth)


[15 32]


[ 1  2  9 11]


Ex26

In [57]:
# save and load numpy array
import numpy as np

first=np.array([10,20,30,40, 50,60,70])
print(first)                    #  array will be printed
np.save("myarray",first)
first=None
print(first)                    # None, no need to worry, we can load the saved array
second=np.load("myarray.npy")   # extension "npy" mandatory
print(second)

[10 20 30 40 50 60 70]
None
[10 20 30 40 50 60 70]


2 d array 

     - set of no of 1 d arrats 

        - shape - 3.4

3 d array 

    - set of 2d arrays

            - shape - 2,3,4

2 d array 

    - axis 0 = to chop something from top to bottom 

    - axis = 1 = to chop someting from left to right 

    - axis = 2 = not possible 

3 d array 
     
     - axis = 0 = no o f 2 d array 

     - axis = 1 = is similaar tyo axis 0 of 2d array, ui.e.chopping something from top to bottom 

     - axis = 2 = is similar to axis 1 of 2d array, ir.r chopping something from left to right 


# **About Axis 1 and 2**
Numpy_Folder\About axis 0 ,1 and 2

with 2d array example 

Sum() function 


in 2d array

axis 0 means  
	chopping something from top to bottom

axis 1 means
	chopping something from left to right

In [61]:
import numpy  as np

myar=np.array([[10,20,30],[40,50,60],[70,80,90]])

print(myar)
print()

print("entire sum")
print(np.sum(myar))
print("axis 0 sum = cols ")
print(np.sum(myar,axis=0))  # chopping something from top to bottom
print("axis 1 sum = rows")
print(np.sum(myar,axis=1))  # chopping something from left to right

[[10 20 30]
 [40 50 60]
 [70 80 90]]

entire sum
450
axis 0 sum = cols 
[120 150 180]
axis 1 sum = rows
[ 60 150 240]


3d array 

in 3d array

axis 0 means
	no. of 2d arrays

axis 1 means  
	chopping something from top to bottom

axis 2 means
	chopping something from left to right

In [66]:
import numpy  as np

myar=np.array([10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27])

myar.shape=(2,3,3)
print(myar)

print("Total sum = ",np.sum(myar))
print()
print("Axis 0 sum = \n",np.sum(myar,axis=0)) # put 2nd two d array after first 2d array and then sum

print()
print("with axis 1")
print("Axis 1 sum sum = \n",np.sum(myar,axis=1)) # it's like axis=0 in 2d array , chopping something from top to bottom within each 2d array

print()
print("with axis 2")
print("Axis 0 sum = \n", np.sum(myar,axis=2)) # it's like axis=1 in 2d array, chopping something from left to right within each 2d array


[[[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
Total sum =  333

Axis 0 sum = 
 [[29 31 33]
 [35 37 39]
 [41 43 45]]

with axis 1
Axis 1 sum sum = 
 [[39 42 45]
 [66 69 72]]

with axis 2
Axis 0 sum = 
 [[33 42 51]
 [60 69 78]]


## **All about stack**

- Numpy_Folder\Example_11_All_about_stack

In [120]:
i = iter('GFG')

print(next(i))
print(next(i))

print(next(i))

print(next(i))



G
F
G


StopIteration: 

In [68]:
import numpy as np

arr1= np.array([10,20,30])
arr2=np.array([40,50,60])

hstack1=np.hstack((arr1,arr2))
print("Let's print horizontal stack")
print(hstack1)
print(hstack1.ndim)
print(hstack1.shape)
"""
[10 20 30 40 50 60]   horizontally stacked
"""

vstack1=np.vstack((arr1,arr2))
print("Let's print vertical stack")
print(vstack1)
print(vstack1.ndim)
print(vstack1.shape)
"""
[[10 20 30]
 [40 50 60]]         vertically stacked

"""
dstack1=np.dstack((arr1,arr2))
print("Let's print d stack")
print(dstack1)
print(dstack1.ndim)
print(dstack1.shape)

"""
[[[10 40]
  [20 50]
  [30 60]]]    depth i.e. 0th element of both the arrays will be joined ,
  then 1st element of both the arrays will be joined and so on
"""

zerostack=np.stack((arr1,arr2),axis=0)  #  top to bottom
print("let's print axis-0 stack")
print(zerostack)
print(zerostack.ndim)
print(zerostack.shape)

"""
[[10 20 30]
 [40 50 60]]  it's a double dimension array, first array is placed at 0th row and second at 1st row

"""

onestack=np.stack((arr1,arr2),axis=1)  #  left to right
print("let's print axis-1 stack")
print(onestack)
print(onestack.ndim)
print(onestack.shape)

"""
[[10 40]
 [20 50]
 [30 60]]
		it like first array is taken and stacked at 0th column and second is stacked at 1st column
"""

#  np.stack((arr1,arr2),axis=2)  # not possible


Let's print horizontal stack
[10 20 30 40 50 60]
1
(6,)
Let's print vertical stack
[[10 20 30]
 [40 50 60]]
2
(2, 3)
Let's print d stack
[[[10 40]
  [20 50]
  [30 60]]]
3
(1, 3, 2)
let's print axis-0 stack
[[10 20 30]
 [40 50 60]]
2
(2, 3)
let's print axis-1 stack
[[10 40]
 [20 50]
 [30 60]]
2
(3, 2)


'\n[[10 40]\n [20 50]\n [30 60]]\n\t\tit like first array is taken and stacked at 0th column and second is stacked at 1st column\n'

2d array 

In [69]:
import numpy as np

arr1= np.array([[10,20,30],[40,50,60]])
arr2=np.array([[70,80,90],[100,110,120]])

hstack1=np.hstack((arr1,arr2))
print("Let's print horizontal stack")
print(hstack1)
"""
[[ 10  20  30  70  80  90]     horizontally stacked
 [ 40  50  60 100 110 120]]
"""
vstack1=np.vstack((arr1,arr2))
print("Let's print vertical stack")
print(vstack1)
"""
[[ 10  20  30]			vertically stacked
 [ 40  50  60]
 [ 70  80  90]
 [100 110 120]]

"""
dstack1=np.dstack((arr1,arr2))
print("Let's print d stack")
print(dstack1)

"""
[[[ 10  70]    first array's 0th element second's 0th element and so on....
  [ 20  80]
  [ 30  90]]

 [[ 40 100]
  [ 50 110]
  [ 60 120]]]
"""

zerostack=np.stack((arr1,arr2),axis=0)
print("let's print axis-0 stack")
print(zerostack)

"""
since it is going to create 3d array, in 3d array first is no. of 2d arrays
so both 2d arrays are just stacked one below another

[[[ 10  20  30]
  [ 40  50  60]]

 [[ 70  80  90]
  [100 110 120]]]
"""

onestack=np.stack((arr1,arr2),axis=1)
print("let's print axis-1 stack")
print(onestack)

"""

since it is going to create 3d array, in 3d array second is no. of rows
so both 2d arrays 0th rows and 1st rows are stacked one below another

[[[ 10  20  30]        # 0th row of first 2d array
  [ 70  80  90]]       # 0th row of second 2d array

 [[ 40  50  60]        # 1st row of first 2d array
  [100 110 120]]]      # 1st row of second 2d array

"""

twostack=np.stack((arr1,arr2),axis=2)
print("let's print axis-2 stack")
print(twostack)

"""

since it is going to create 3d array, in 3d array third is no. of cols
hence 1st 2d arrays 0th row and 2nd 2d arrays 0th row are placed in the columns 0 and 1 respectively. 
Similarly 1st 2d arrays 1st row and 2nd 2d arrays 1st row are placed in the columns 0 and 1 respectively.


[[[ 10  70]
  [ 20  80]
  [ 30  90]]

 [[ 40 100]
  [ 50 110]
  [ 60 120]]]


"""

Let's print horizontal stack
[[ 10  20  30  70  80  90]
 [ 40  50  60 100 110 120]]
Let's print vertical stack
[[ 10  20  30]
 [ 40  50  60]
 [ 70  80  90]
 [100 110 120]]
Let's print d stack
[[[ 10  70]
  [ 20  80]
  [ 30  90]]

 [[ 40 100]
  [ 50 110]
  [ 60 120]]]
let's print axis-0 stack
[[[ 10  20  30]
  [ 40  50  60]]

 [[ 70  80  90]
  [100 110 120]]]
let's print axis-1 stack
[[[ 10  20  30]
  [ 70  80  90]]

 [[ 40  50  60]
  [100 110 120]]]
let's print axis-2 stack
[[[ 10  70]
  [ 20  80]
  [ 30  90]]

 [[ 40 100]
  [ 50 110]
  [ 60 120]]]


'\n\nsince it is going to create 3d array, in 3d array third is no. of cols\nhence 1st 2d arrays 0th row and 2nd 2d arrays 0th row are placed in the columns 0 and 1 respectively. Similarly 1st 2d arrays 1st row and 2nd 2d arrays 1st row are placed in the columns 0 and 1 respectively.\n\n\n[[[ 10  70]\n  [ 20  80]\n  [ 30  90]]\n\n [[ 40 100]\n  [ 50 110]\n  [ 60 120]]]\n\n\n'

One more example 

In [70]:
import numpy as np

arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[7,8,9],[10,11,12]])
arr3=np.array([[13,14,15],[16,17,18]])

hstack=np.hstack((arr1,arr2,arr3))
print("this is hstack")
print(hstack) # each 2d array's individual rows are stacked horizontally

vstack=np.vstack((arr1,arr2,arr3))
print("this is vstack")
print(vstack) # each 2d array is stacked vertically

dstack=np.dstack((arr1,arr2,arr3))
print("this is dstack")
print(dstack) # each 2d array's individual member is stacked together

stack_0=np.stack((arr1,arr2,arr3),axis=0)
print("this is 0 stack")
print(stack_0)  # in 3d array, axis 0 means no. of 2d arrays
# here we have 3 2d arrays , so they are stacked one below other

stack_1=np.stack((arr1,arr2,arr3),axis=1)
print("this is 1 stack")
print(stack_1)  # in 3d array axis 1 is similar to axis 0 of 2d array
# i.e. top to bottom
# each 2d array's 0th rows are stacked from top to bottom , then 1st rows and so on

stack_2=np.stack((arr1,arr2,arr3),axis=2)
print("this is 2 stack")
print(stack_2) # in 3d array axis 2 is similar to axis 1 of 2d array
# i.e. left to right
# each 2d array's 0th row will be placed in the 0th column, 1st and 2nd column respectively
# in the first generated 2d array
# each 2d array's 1th row will be placed in the 0th column, 1st and 2nd column respectively
# in the second generated 2d array.

print(stack_2.ndim)
print(stack_2.shape)

this is hstack
[[ 1  2  3  7  8  9 13 14 15]
 [ 4  5  6 10 11 12 16 17 18]]
this is vstack
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
this is dstack
[[[ 1  7 13]
  [ 2  8 14]
  [ 3  9 15]]

 [[ 4 10 16]
  [ 5 11 17]
  [ 6 12 18]]]
this is 0 stack
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
this is 1 stack
[[[ 1  2  3]
  [ 7  8  9]
  [13 14 15]]

 [[ 4  5  6]
  [10 11 12]
  [16 17 18]]]
this is 2 stack
[[[ 1  7 13]
  [ 2  8 14]
  [ 3  9 15]]

 [[ 4 10 16]
  [ 5 11 17]
  [ 6 12 18]]]
3
(2, 3, 3)


# **Concat - numpy**

Concate_Numpy

In [116]:
""" NumPy stack() vs. concatenate()

the concatenate() function joins elements of two arrays along an existing axis while the stack() function joins the two arrays along a new axis. This means when we use "stack",the resulting array will have one more dimension than the input arrays.
 """
import numpy as np

a = np.array([1,2])
b = np.array([3,4])

c = np.concatenate((a,b)) # return 1-D array                    
d = np.stack((a,b)) # return 2-D array
print("concat output")
print(c)
print("stack output")
print(d)

concat output
[1 2 3 4]
stack output
[[1 2]
 [3 4]]


In [72]:
# concate 1 d arrays

import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr3=np.concatenate((arr1,arr2)) #  it will make one single array containing arr1 and arr2 values
print(arr3)    #  [1 2 3 4 5 6]


[1 2 3 4 5 6]


In [76]:
# concate and stack 2d arrays with axis=0
# axis=0 means from top to bottom

import numpy as np
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[7,8,9],[10,11,12]])
arr3=np.concatenate((arr1,arr2),axis=0) #  keep arr1 and arr2 one below other,and create 2d array
print("output of concat")
print(arr3)    

"""
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

"""
print("dimension of new array after concat function is\t",arr3.ndim)
print("shape of new array after concat function is\t",arr3.shape)
print()
print()
print("output of stack")
arr4=np.stack((arr1,arr2),axis=0)    #  keep arr1 and arr2 one below other,and create 3d array
print(arr4)

"""
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

"""
print("dimension of new array after stack function is\t",arr4.ndim)
print("shape of new array after stack function is\t",arr4.shape)

print()

arr4=np.stack((arr1,arr2),axis=1) 
print(arr4)
print("dimension of new array after stack function is\t",arr4.ndim)
print("shape of new array after stack function is\t",arr4.shape)



output of concat
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
dimension of new array after concat function is	 2
shape of new array after concat function is	 (4, 3)


output of stack
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
dimension of new array after stack function is	 3
shape of new array after stack function is	 (2, 2, 3)

[[[ 1  2  3]
  [ 7  8  9]]

 [[ 4  5  6]
  [10 11 12]]]
dimension of new array after stack function is	 3
shape of new array after stack function is	 (2, 2, 3)


In [78]:
# with stack
# axis 0,1 and 2 all are possible for stack in the following case


import numpy as np
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[7,8,9],[10,11,12]])
print(arr1.ndim)
print(arr2.ndim)
arr3=np.stack((arr1,arr2),axis=0)
print(arr3)
print(arr3.ndim)
print(arr3.shape)
print("*********")
arr3=np.stack((arr1,arr2),axis=1)
print(arr3)
print(arr3.ndim)
print(arr3.shape)
print("*********")
arr3=np.stack((arr1,arr2),axis=2)
print(arr3)
print(arr3.ndim)
print(arr3.shape)


# with concat


arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[7,8,9],[10,11,12]])

# in the above case 
# 	np.stack
# 		axis 0,axis 1 and axis 2 all are possible

# 	np.concat
# 		axis 0 and axis 1 are possible
# 		but axis 2 is not possible,it says
# 			axis 2 is out of bounds for array of dimension 2
# 	why it is so?

arr3=np.concatenate((arr1,arr2),axis=0)
print(arr3)
print(arr3.ndim)
print(arr3.shape)


# [[ 1  2  3]
#  [ 4  5  6]
#  [ 7  8  9]
#  [10 11 12]]

	# dimension 2  [ does not change the dimension of the resulting array which is correct as per "concat" method ]
	# shape - 4,3


arr3=np.concatenate((arr1,arr2),axis=1)
print(arr3)
print(arr3.ndim)
print(arr3.shape)

# [[ 1  2  3  7  8  9]
#  [ 4  5  6 10 11 12]]

	# dimension 2  [ does not change the dimension of the resulting array which is correct as per "concat" method ]

	# shape - 2,6


arr3=np.concatenate((arr1,arr2),axis=2) # it will not work, but let's assume it works. now let's see what is the side effect of this.
print(arr3)
print(arr3.ndim)
print(arr3.shape)


# 1  7
# 2  8
# 3  9

# 4  10
# 5  11
# 6  12

# 	dimension 3  [ it will change the dimension of the resulting array which is not correct as per "concat" method. this should not happen that's why here "axis-2" gives error]
# 	shape - 2,3,2

2
2
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3
(2, 2, 3)
*********
[[[ 1  2  3]
  [ 7  8  9]]

 [[ 4  5  6]
  [10 11 12]]]
3
(2, 2, 3)
*********
[[[ 1  7]
  [ 2  8]
  [ 3  9]]

 [[ 4 10]
  [ 5 11]
  [ 6 12]]]
3
(2, 3, 2)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
2
(4, 3)
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
2
(2, 6)


AxisError: axis 2 is out of bounds for array of dimension 2

# **Numpy_Folder\Example_14_Numpy_Mathematical**

Ex14

In [79]:
# axis-0 for top to bottom sum
# axis-1 for left to right sum

import numpy as np

first=np.array([10,20,30])
second=np.array([40,50,60])
third=np.sum((first,second),axis=0)     # top to bottom
# [50 70 90]
print(third)
print("\n\n")
fourth=np.sum((first,second),axis=1)    # left to right
# [ 60 150]
print(fourth)



[50 70 90]



[ 60 150]


In [80]:
# axis=0  top to bottom sum
# axis=1  left to right sum

import numpy as k
arr=k.array([[1,2,3,4],
             [2,3,4,5],
             [7,8,9,10]])
arr1=k.sum(arr,axis=1)   # left to right sum
# 1+2+3+4   2+3+4+5   7+8+9+10
print(arr1)

arr2=k.sum(arr,axis=0)  # top to bottom sum
# 1+2+7     2+3+8     3+4+9     4+5+10
print(arr2)

[10 14 34]
[10 13 16 19]


Ex14b

In [ ]:
import numpy as np

fourth=np.array([[10,20,30],[40,50,60]])
fifth=np.array([[70,80,90],[100,110,120]])
sixth=np.sum((fourth,fifth),axis=0)
"""
in case of 3d array axis 0 means no.of 2d arrays
here we have 2 2d arrays , so in axis 0 what happens
is second 2d array is placed behind 1st 2d array and sum is performed
on each and every element i.e. 10 is added to 70, 20 is added to 80 and so on....
"""
print(sixth)
""" [[ 80 100 120] 
     [140 160 180]] """
print("\n")
eighth=np.sum((fourth,fifth),axis=1)
"""
in 3d array axis 1 is similar to axis 0 of 2d array i.e. top to bottom
so each 2d arrays sum will be calculated based of top to bottom pattern
it means 10 is added to 40, 20 is added to 50 and so..on
"""
print(eighth)
""" [[ 50  70  90] 
 [170 190 210]] """
print()
ninth=np.sum((fourth,fifth),axis=2)
"""
in 3d array axis 2 means axis 1 of 2d array i.e. left to right
so each 2d arrays sum will be calculated on left to right pattern
it means 10+20+30   40+50+60   70+80+90   100+110+120 
"""
print(ninth)
""" [[ 60 150]     
 [240 330]] """ 

Ex15

In [ ]:
import numpy as np
print("Let's try with 3 arrays")
a=np.array([[10,20,30],[40,50,60]])
b=np.array([[70,80,90],[100,110,120]])
c=np.array([[5,9,11],[15,17,18]])
print("output of axis=0")
print("**************")
d=np.sum((a,b,c),axis=0)      
print(d)
""" [[ 85 109 131]  
 [155 177 198]] """ 
print("output of axis=1")
print("*************")
e=np.sum((a,b,c),axis=1)
print(e)
""" [[ 50  70  90]  
 [170 190 210]  
 [ 20  26  29]] """
print("output of axis=2")
print("************")
f=np.sum((a,b,c),axis=2)
print(f)
""" [[ 60 150]
 [240 330]
 [ 25  50]] """

# **Sort Numpy**

- Numpy_Folder\Sort_NumPy

In [81]:
import numpy as np
 
a = np.array([12, 15, 10, 1])
print("Array before sorting",a)
a.sort()
print("Array after sorting",a)

Array before sorting [12 15 10  1]
Array after sorting [ 1 10 12 15]


In [82]:
import numpy as np

# sort without any axis

a = np.array([[12, 25], [30, 18]])
arr1 = np.sort(a, axis=None)
print("\nAlong None axis : \n", arr1)



Along None axis : 
 [12 18 25 30]


In [83]:
# sort along the first axis
a = np.array([[12, 25], [30, 18]])
arr1 = np.sort(a, axis=0) # top to bottom
# 12 will be compared with 30, 25 will be compared with 18
print("Along 0 axis : \n", arr1)

Along 0 axis : 
 [[12 18]
 [30 25]]


here for descending order we have said


a = np.array([[12, 25], [30, 18]])

print("Reverse order axis 0\n")
arr1 = -np.sort(-a, axis=0)
print(arr1)

why two minus(-) signs are required here? one for np.sort and other for "a"




First Minus (-a): This negates the elements of the array a. So, for example, the array [[12, 25], [30, 18]] becomes [[-12, -25], [-30, -18]]. 
This transformation effectively flips the values, allowing larger original values to become smaller (in terms of their negated values).



np.sort(-a, axis=0): Now, when you apply np.sort to the negated array, it sorts the values in ascending order. 
For the transformed array, this means the larger original values will appear first.



Second Minus (-np.sort(-a, axis=0)): Finally, you negate the sorted result again to return it to the original scale. This gives you the values in descending order.

In [ ]:

a = np.array([[12, 25], [30, 18]])
arr1 = np.sort(a, axis=1) # left to right
# 12 will be compared to 25, 30 will be compared to 18
print("\nAlong 1 axis : \n", arr1)

print("Reverse order top to bottom\n")
arr1 = -np.sort(-a, axis=0)
print(arr1)


print("Reverse order left to right\n")
arr1 = -np.sort(-a, axis=1)
print(arr1)


print("****************")


myar = np.array([[[10, 20, 30], [4, 50, 6]], [[70, 8, 90], [65, 110, 12]]])
print(myar)
print("Ascending order 3d array axis 0")
arr1 = np.sort(myar, axis=0)


"""
in 3d array axis 0 means no. of 2d arrays. Since we have 2 2d arrays
each and every element of 1st 2d array will be compared with 2nd 2d array

10 will be compared with 70, 20 will be with 8, 30 will be with 90
4 will be with 65, 50 will be with 110, 6 will be with 12
"""

print(arr1)
print("Ascending order 3d array axis 1")
arr1 = np.sort(myar, axis=1)

""" 
in 3d array axis 1 means axis 0 of 2d array i.e. top to bottom
so in each 2d array elements will be compared on top to bottom basis
i.e.
10 will be compared with 4, 20 will be with 50, 30 will be compared with 6
70 will be compared with 65, 8 will be compared with 110, 90 will be compared with 12"""

print(arr1)

print("Ascending order 3d array axis 2")
arr1 = np.sort(myar, axis=2)

"""
in 3d array axis 2 means axis 1 of 2d array which means left to right
so each individual array of each 2d array will be compared from left to right
i.e. 10 will be compared with 20 and 30
4 will be compared with 50 and 60
and so on....
"""
print(arr1)
print("Reverse order 3d array axis 0\n")
arr1 = -np.sort(-myar, axis=0)
print(arr1)
print("Reverse order 3d array axis 1\n")

arr1 = -np.sort(-myar, axis=1)
print(arr1)
print("Reverse order 3d array axis 2\n")

arr1 = -np.sort(-myar, axis=2)
print(arr1)

# **Indexing - slicing - 1d array**

In [84]:
from numpy import *

first=array([10,20,30,40])
# indexing from left to right

print(first[0],"\t",first[1],"\t",first[2],"\t",first[3])

# indexing from right to left

print("\n")
print(first[-1],"\t",first[-2],"\t",first[-3],"\t",first[-4])

10 	 20 	 30 	 40


40 	 30 	 20 	 10


In [85]:
from numpy import *

first=array([10,20,30,40,50,60])
print(first)
print("\n")
second=first[2:4]    #  4 is exclusive
print("after slicing")
print(second)
third=first[1:5:2]     #  2 is a skip value,  if not given it is by default 1
print("\n")
print(third)
fourth=first[3:]       #  start from the 3rd position and go till end
print("\n")
print(fourth)
print("\n")
fifth=first[:4]        #  start from 0 and go till 3 ,  4 is exclusive
print(fifth)
sixth=first[-2:]       #  last two elements   , start from second last and go till end
print("\n")
print(sixth)
print("\n")
seventh=first[:-2]     # start from zero and go till second last,   second last is exclusive
print(seventh)
eighth=first[-4:-1]    # start from -4 i.e. number 30  and go till last , last is exclusive
print("\n")
print(eighth)

[10 20 30 40 50 60]


after slicing
[30 40]


[20 40]


[40 50 60]


[10 20 30 40]


[50 60]


[10 20 30 40]


[30 40 50]


# **Indexing - slicing - 2d array**

In [86]:
from numpy import *

first=array([[10,20,30],[40,50,60],[70,80,90]])
print("from left to right")
print(first[0][0])
print(first[0][1])
print(first[0][2])
print(first[1][0])
print(first[1][1])
print(first[1][2])
print(first[2][0])
print(first[2][1])
print(first[2][2])
print("from right to left")
print(first[-1][-1])
print(first[-1][-2])
print(first[-1][-3])
print(first[-2][-1])
print(first[-2][-2])
print(first[-2][-3])
print(first[-3][-1])
print(first[-3][-2])
print(first[-3][-3])


from left to right
10
20
30
40
50
60
70
80
90
from right to left
90
80
70
60
50
40
30
20
10


slicing 1 

In [87]:
from numpy import *

first=array([[10,20,30],[40,50,60],[70,80,90]])
# slicing syntax
#  arrayname [row range,col range]

second=first[:2]     # start from 0th row and go till 2nd row,   2 is exclusive  this is only for row as you haven't given column

print(second)

third=first[:2,1:3]  #  row 0 to 1    column 1 to 2  , 3 is exclusive
print(third)

[[10 20 30]
 [40 50 60]]
[[20 30]
 [50 60]]


Slicing 2 

In [88]:
from numpy import *

random.seed(8)
first=random.randint(1,500,30).reshape(6,5)
print("array created is")
print(first)
print("from the 2nd row")
print(first[2:])            #  from 2nd row
print("\n")
print(first[2:,3])          #  from 2nd row and only 3rd column
print("\n")
print(first[2:,2:])         #  from 2nd row and from 2nd column
# let's extract  459  62  and 19
print("\n")
print(first[3:,1:2])
# let's extract 340 361 86 317 156 and 109
print("\n")
print(first[1:4,2:4])
print("\n")
# let's extract  459  156  and 109
print(first[3:4,1:4])

array created is
[[452 341 498 362 134]
 [475 137 340 361 192]
 [ 49 366  86 317 434]
 [116 459 156 109 270]
 [394  62 144 350 355]
 [316  19 271 103 350]]
from the 2nd row
[[ 49 366  86 317 434]
 [116 459 156 109 270]
 [394  62 144 350 355]
 [316  19 271 103 350]]


[317 109 350 103]


[[ 86 317 434]
 [156 109 270]
 [144 350 355]
 [271 103 350]]


[[459]
 [ 62]
 [ 19]]


[[340 361]
 [ 86 317]
 [156 109]]


[[459 156 109]]


# **Filtering in numpy**

1) Using mask [ based on multiple conditions]

2) Iterative method

3) Using lambda

Ex1

In [89]:
import numpy as np

arr = np.array([5,8,9,11,12,16])
print(arr)
print(arr[[True,False,True,False,True,False]])


[ 5  8  9 11 12 16]
[ 5  9 12]


Ex2

In [90]:
import numpy as np

arr = np.array([5,8,9,11,12,16])
print(arr)


[ 5  8  9 11 12 16]


In [91]:

print(arr%4==0)  #  it prints  [False  True False False  True  True]


[False  True False False  True  True]


In [92]:

print(arr[(arr%4==0)]) # it's like arr[[False  True False False  True  True]]


[ 8 12 16]


In [93]:

print(arr[(arr>=9) & (arr<=15)])


[ 9 11 12]


In [94]:

print(arr[(arr%3==0) | (arr%11==0)])


[ 9 11 12]


In [99]:

print(arr[(arr%3==0) | (arr%11==0)])

arr = np.array([5,8,9,11,12,16])
print(arr)
#filter for values that are equal to 2, 3, 5, or 12
print(np.isin(arr,[2, 3, 5, 12]))
print("*****************")

print(arr[np.isin(arr,[2, 3, 5, 12])])


[ 9 11 12]
[ 5  8  9 11 12 16]
[ True False False False  True False]
*****************
[ 5 12]


Ex3

In [100]:
# Using mask

import numpy as np
 
# making a numpy array
array1 = np.array([num for num in range(10, 50)])
 
print("Original array")
print(array1)
 
# defining mask based on two conditions:
# array element must be greater than 22
# and must be a divisible by 2
mask = (array1 > 22) & (array1 % 2 == 0)
 
# making new array on conditions
array2 = array1[mask]
print("New array")
print(array2)

Original array
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
New array
[24 26 28 30 32 34 36 38 40 42 44 46 48]


Using iterative method

In [101]:
# Using iterative method

import numpy as np
 
# making a numpy array
array1 = np.array([x for x in range(11, 40)])
 
print("Original array")
print(array1)
 
# making a blank list
mylist = []
 
for x in array1:
    # applying two conditions: number is divisible by 2 and is greater than 15
    if x % 2 == 0 and x > 15:
       mylist.append(x)

# Converting new list into numpy array
array2 = np.array(mylist)
print("New array")
print(array2)

Original array
[11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35 36 37 38 39]
New array
[16 18 20 22 24 26 28 30 32 34 36 38]


uising lambda

In [105]:
# Using Lambda

import numpy as np
 
# making a numpy array
array1 = np.array([num for num in range(1,30)])
 
print("Original array")
print(array1)
 
# using lambda to apply condition
mylist = list(filter(lambda x: x > 15 and x % 3 == 0 and x % 10 != 0, array1))
 
# Converting new list into numpy array
array2 = np.array(mylist)
print("New array")
print(array2)

print("Using list comprehension for numpy filtering")


mylist1=[x for x in array1 if x%5==0]
array2=np.array(mylist1)
print(array2)


Original array
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29]


TypeError: 'list' object is not callable

In [107]:
import numpy as np

array1= np.arange(12).reshape(3,4)
print("original array is\n")
print(array1)
result = array1[array1 > 5]
print("Filter values from array:\n",result)
result1=array1[(array1<10) & (array1%3==0)]
print(result1)

original array is

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Filter values from array:
 [ 6  7  8  9 10 11]
[0 3 6 9]


In [108]:
import numpy as np

# axis=0 top to bottom

# axis=1 left to right

a = np.arange(12).reshape((3, 4))
print(a)
print("***************")


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
***************


'\nnp.all() method return True if all the values fulfills the condition.\nThis return value maps with the original array to give the filtered values\n\n: means all rows\n'

In [110]:
"""
np.all() method return True if all the values fulfills the condition.
This return value maps with the original array to give the filtered values
: means all rows
"""
print(a[:, np.all(a < 10, axis = 0)])
print("*********************")


[[0 1]
 [4 5]
 [8 9]]
*********************


' np.any() method return true if any of the values fulfill the condition.\n This return value maps with the original array to give the filtered values.\n : means all the rows\n '

In [111]:

""" np.any() method return true if any of the values fulfill the condition.
 This return value maps with the original array to give the filtered values.
 : means all the rows
 """
print(a[:,np.any(a < 10, axis = 0)])
print("*******************")

print(a[:,np.any(a > 8, axis = 0)])
print("**************************")


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
*******************
[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]]
**************************


In [112]:
"""
axis=1 means left to right
: here means all the columns
"""
print(a[np.any(a < 10, axis = 1),:])
print("**************************")

print(a[np.all(a < 10, axis = 1),:])

print("selected rows")
print(a[1:3,np.any(a > 8, axis = 0)])   # 1 to 2 rows  , top to bottom

print("selected columns")
print(a[np.all(a < 10, axis = 1),:2])    # 0 to 1 columns , left to right


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
**************************
[[0 1 2 3]
 [4 5 6 7]]
selected rows
[[ 5  6  7]
 [ 9 10 11]]
selected columns
[[0 1]
 [4 5]]


# **numpy mutable or immutable**

Ex1

In [113]:
# numpy array elements are mutable but numpy as an object is immutable
# first+1  creates a new numpy object in which changes can be seen

import numpy as np
first=np.array([10,20,30])
print(first,"\t",id(first))
second=first+1      #  this is like immutable
first[0]=34         #  array elements can be changed
print(first,"\t",id(first))
print(second,"\t",id(second))


[10 20 30] 	 2486623038864
[34 20 30] 	 2486623038864
[11 21 31] 	 2486623038480


Ex2

In [ ]:
# how to make numpy array read only
import numpy as np

first=np.array([10,20,30])
first.flags.writeable = False
print(first,"\t",id(first))
second=first+1      #  no problem here
# first[0]=34         # ValueError: assignment destination is read-only
print(first,"\t",id(first))
print(second,"\t",id(second))