1) create a list, accept 5 numbers , store them in the list and finally convert that list to numpy array.


In [4]:
import numpy as np 
l = []

for i in range(0,5):
    a= int(input("Enter A values to Append to list :: "))
    l.append(a)

array = np.array(l)

print(array)
print(type(array))

[1 2 3 4 5]
<class 'numpy.ndarray'>


2) create numpy array of 5 numbers and print their sum


In [5]:
print(array)

n = np.sum(array)

print(n)

[1 2 3 4 5]


15

3) create numpy double dimension array of 3*3 to store your initial and display them in a tabular form.


In [9]:
p = np.full((3,3), 'P')
print(p)
print(type(p))
print(p.ndim)

[['P' 'P' 'P']
 ['P' 'P' 'P']
 ['P' 'P' 'P']]
<class 'numpy.ndarray'>
2


4) create one-d numpy array of 12 elements , accept 12 numbers and display them. Now convert this one-d array into (4*3) two-d array and display it in a tabular form.


In [20]:
one = []

for i in range(0,12):
    a = int(input("Enter value to append to list ::--> "))
    one.append(a)

b = np.array(one)
print(b)

b = b.reshape(4,3)
print(b)
print(type(b))
print(b.shape)
print(b.ndim)

[ 1  2  3  4  5  6  7  8  9  1  0 11]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [ 1  0 11]]
<class 'numpy.ndarray'>
(4, 3)
2


5) create two double dimension array and arrange (stack) them using "axis=0" "axis=1" and  "axis=2".


In [27]:
one = np.array([10,20,30,40])
two = np.array([50,60,70,80])

three = np.stack((one, two), axis=0)
four = np.stack((one, two), axis=1)
# five = np.stack((one, two), axis=2)       won't work as its an 2d array 
print(three)
print()
print(four)
# print(five)


[[10 20 30 40]
 [50 60 70 80]]

[[10 50]
 [20 60]
 [30 70]
 [40 80]]


6) create two one-d arrays and then find out:
	- a) common elements of both the array
	- b) unique elements of first array
	- c) unique elements of second array


In [32]:
one = np.array([10,20,30,80,90])
two = np.array([20,50,80,40,30])

print('----------------A----------------')

a = np.intersect1d(one, two)
print("Common Elements of both the arrays----> ",a)

print('----------------B----------------')
b = np.unique(one)
print(b)

print('----------------C----------------')
c = np.unique(two)
print(c)

----------------A----------------
Common Elements of both the arrays---->  [20 30 80]
----------------B----------------
[10 20 30 80 90]
----------------C----------------
[20 30 40 50 80]


7) accept no.of rows and no. of cols from the user , create two-d array accordingly. Now calculate the sum as per "axis=0" and "axis=1"


In [40]:
row= int(input("Enter number of Row ---> "))
column = int(input("Enter Column of Row ---> "))

a = []

for i in range(0, (row*column)):
    b = int(input("Enter values to append to list ---> "))
    a.append(b)

a = np.reshape(a, (row, column))

a0 = np.sum(a, axis=0)
print("Axis = 0 Sum --> ", a0)

a1 = np.sum(a, axis=1)
print("Axis = 1 Sum --> ",a1)

Axis = 0 Sum -->  [5 7 9]
Axis = 1 Sum -->  [ 6 15]


8) declare two 2d arrays and calculate the sum as per "axis=0" "axis=1" and "axis=2"


In [44]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[7,8,9],[10,11,12]])

a0 = np.sum(a, axis=0)
print("Axis = 0 Sum --> ", a0)

a1 = np.sum(a, axis=1)
print("Axis = 1 Sum --> ",a1)

# a2 = np.sum(a, axis=2)
# print("Axis = 1 Sum --> ",a2)     won't work on 2d only works on 3d array

Axis = 0 Sum -->  [5 7 9]
Axis = 1 Sum -->  [ 6 15]


9) create two-d array ,display it. Now accept a number from user and perform all arithmetic operations on each and every element of the array using that number.


In [54]:
a = np.array([[1,2,3],[4,5,6]])
print("A --> ", a)
print("------------------------------------")
b = np.array([[7,8,9],[10,11,12]])
print("B --> ", b)
print("------------------------------------")

c = int(input("Enter a number to perform various operations --> "))

print(f"Addition of user input {c} with array \n",  np.add(a, c))
print("------------------------------------")

print(f"Substraction of user input {c} with array \n",  np.subtract(a, c))
print("------------------------------------")

print(f"multiply of user input {c} with array \n",  np.multiply(a, c))
print("------------------------------------")

print(f"divide of user input {c} with array \n",  np.divide(a, c))
print("------------------------------------")

print(f"mod of user input {c} with array \n",  np.mod(a, c))
print("------------------------------------")

print(f"floor_divide of user input {c} with array \n",  np.floor_divide(a, c))

A -->  [[1 2 3]
 [4 5 6]]
------------------------------------
B -->  [[ 7  8  9]
 [10 11 12]]
------------------------------------
Addition of user input 5 with array 
 [[ 6  7  8]
 [ 9 10 11]]
------------------------------------
Substraction of user input 5 with array 
 [[-4 -3 -2]
 [-1  0  1]]
------------------------------------
multiply of user input 5 with array 
 [[ 5 10 15]
 [20 25 30]]
------------------------------------
divide of user input 5 with array 
 [[0.2 0.4 0.6]
 [0.8 1.  1.2]]
------------------------------------
mod of user input 5 with array 
 [[1 2 3]
 [4 0 1]]
------------------------------------
floor_divide of user input 5 with array 
 [[0 0 0]
 [0 1 1]]


10) accept start, end and how many numbers to be generated and then using "linspace" create numpy array.


In [58]:
print(np.linspace.__doc__)


    Return evenly spaced numbers over a specified interval.

    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].

    The endpoint of the interval can optionally be excluded.

    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.

    .. versionchanged:: 1.20.0
        Values are rounded towards ``-inf`` instead of ``0`` when an
        integer ``dtype`` is specified. The old behavior can
        still be obtained with ``np.linspace(start, stop, num).astype(int)``

    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that `stop` is excluded.  Note that the step
        size changes when `endpoint` is False.
    num : int, optional
        Number of samples to gen

In [61]:
start = int(input("Enter a start Number --> "))

end = int(input("Enter a end Number  --> "))

np.linspace(start, end, 10)

array([10.        , 15.55555556, 21.11111111, 26.66666667, 32.22222222,
       37.77777778, 43.33333333, 48.88888889, 54.44444444, 60.        ])

11) create one-d array of 8 numbers and then using "slicing" concept,
	- a) print numbers from 1 to 4
	- b) print all the numbers from 3rd position
	- c) print last 3 numbers


In [67]:
a = np.array([1,2,3,4,5,6,7,8])

print(a[1:4])

print(a[3:])

print(a[-3:])

[2 3 4]
[4 5 6 7 8]
[6 7 8]


12) create 2 d array (4*3) with following values:

[[10,20,30,40],[50,60,70,80],[90,100,110,120]]


In [70]:
a = np.array([[10,20,30,40],[50,60,70,80],[90,100,110,120]])

b = np.reshape(a, (4,3))
print(b)

[[ 10  20  30]
 [ 40  50  60]
 [ 70  80  90]
 [100 110 120]]


now using array slicing concept display following values
- a) display   50  60  70  80
- b) display 100 and 110
- c) display 30 70 and 110
- d) display 50  60  90 and 100


In [71]:
print(a)

[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]


In [72]:
print(a[1])

[50 60 70 80]


In [75]:
print(a[2:3,1:3])

[[100 110]]


In [78]:
print(a[:, 2])

[ 30  70 110]


In [81]:
print(a[1:3, 0:2])

[[ 50  60]
 [ 90 100]]
